/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type TeamMemberReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "teamMember";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  aboutBlurb?: string;
  bookingLabel?: string;
  bookingUrl?: string;
  workTabLabel?: string;
  aboutTabLabel?: string;
  allFilterLabel?: string;
  projectOrder?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
  teamOrder?: Array<
    {
      _key: string;
    } & TeamMemberReference
  >;
  teamBlurb?: string;
  contactPrefix?: string;
  contactEmail?: string;
  seoTitle?: string;
  seoDescription?: string;
  canonicalUrl?: string;
  themeColor?: string;
  socialImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  url?: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  navIcon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<string>;
  linkType?: "listing" | "detail" | "external";
  summary?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  previewImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  previewVideo?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  publishedAt?: string;
  featured?: boolean;
  projectUrl?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ProjectReference
  | TeamMemberReference
  | SanityImageAssetReference
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | TeamMember
  | SanityFileAssetReference
  | Project
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../fruitjamms/src/utils/sanity.ts
// Variable: SITE_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0] {    siteName,    aboutBlurb,    bookingLabel,    bookingUrl,    workTabLabel,    aboutTabLabel,    allFilterLabel,    teamBlurb,    contactPrefix,    contactEmail,    seoTitle,    seoDescription,    canonicalUrl,    themeColor,    socialImage,    projectOrder[]->{      _id,      title,      slug,      categories,      linkType,      projectUrl,      previewImage,      "previewVideoUrl": previewVideo.asset->url    },    teamOrder[]->{      _id,      name,      role,      url,      avatar    }  }
export type SITE_QUERY_RESULT = {
  siteName: string | null;
  aboutBlurb: string | null;
  bookingLabel: string | null;
  bookingUrl: string | null;
  workTabLabel: string | null;
  aboutTabLabel: string | null;
  allFilterLabel: string | null;
  teamBlurb: string | null;
  contactPrefix: string | null;
  contactEmail: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
  canonicalUrl: string | null;
  themeColor: string | null;
  socialImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  projectOrder: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    categories: Array<string> | null;
    linkType: "detail" | "external" | "listing" | null;
    projectUrl: string | null;
    previewImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    previewVideoUrl: string | null;
  }> | null;
  teamOrder: Array<{
    _id: string;
    name: string | null;
    role: string | null;
    url: string | null;
    avatar: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0] {\n    siteName,\n    aboutBlurb,\n    bookingLabel,\n    bookingUrl,\n    workTabLabel,\n    aboutTabLabel,\n    allFilterLabel,\n    teamBlurb,\n    contactPrefix,\n    contactEmail,\n    seoTitle,\n    seoDescription,\n    canonicalUrl,\n    themeColor,\n    socialImage,\n    projectOrder[]->{\n      _id,\n      title,\n      slug,\n      categories,\n      linkType,\n      projectUrl,\n      previewImage,\n      "previewVideoUrl": previewVideo.asset->url\n    },\n    teamOrder[]->{\n      _id,\n      name,\n      role,\n      url,\n      avatar\n    }\n  }\n': SITE_QUERY_RESULT;
  }
}
